ALTER TABLE usernotification ALTER COLUMN type TYPE varchar(255);
UPDATE usernotification SET type = 'ASSIGNROLE' WHERE type LIKE '0';
UPDATE usernotification SET type = 'REVOKEROLE' WHERE type LIKE '1';
UPDATE usernotification SET type = 'CREATEDV' WHERE type LIKE '2';
UPDATE usernotification SET type = 'CREATEDS' WHERE type LIKE '3';
UPDATE usernotification SET type = 'CREATEACC' WHERE type LIKE '4';
UPDATE usernotification SET type = 'MAPLAYERUPDATED' WHERE type LIKE '5';
UPDATE usernotification SET type = 'MAPLAYERDELETEFAILED' WHERE type LIKE '6';
UPDATE usernotification SET type = 'SUBMITTEDDS' WHERE type LIKE '7';
UPDATE usernotification SET type = 'RETURNEDDS' WHERE type LIKE '8';
UPDATE usernotification SET type = 'PUBLISHEDDS' WHERE type LIKE '9';
UPDATE usernotification SET type = 'REQUESTFILEACCESS' WHERE type LIKE '10';
UPDATE usernotification SET type = 'GRANTFILEACCESS' WHERE type LIKE '11';
UPDATE usernotification SET type = 'REJECTFILEACCESS' WHERE type LIKE '12';
UPDATE usernotification SET type = 'FILESYSTEMIMPORT' WHERE type LIKE '13';
UPDATE usernotification SET type = 'CHECKSUMIMPORT' WHERE type LIKE '14';
UPDATE usernotification SET type = 'CHECKSUMFAIL' WHERE type LIKE '15';
UPDATE usernotification SET type = 'CONFIRMEMAIL' WHERE type LIKE '16';